### ISSUE TITLE
wrongUrlForUpload  - looks google chanegs upload URL

### ISSUE THREAD

**Issue by yarcherny** [Akrog/gcs-client#1]
it looks google changed upload URL from https://www.googleapis.com/storage/... 
to https://www.googleapis.com/upload/storage/...

you should fix it like this

[patch.txt](https://github.com/Akrog/gcs-client/files/601432/patch.txt)

<img width="748" alt="screenshot_3" src="https://cloud.githubusercontent.com/assets/23579193/20455344/a0230496-ae6a-11e6-80f7-c4f021213a02.png">

**Comment by Akrog** [comment]
@yarcherny thanks for the bug report and providing the patch!!

The patch has been included in latest v0.2.2, available in PyPi, and media uploads are working again.
